org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.jetifier.ignorelist=armeabi_v7a_debug,arm64_v8a_debug,x86_64_debug,x86_debug
org.gradle.java.home=C\:/Program Files/Java/jdk-17